### PR TITLE
Updating NSG rules as nested template

### PR DESCRIPTION
**Pull request by sanjaymantoor**
NSG rules are updated with default access to Azure network, but can gain access by adding public ip to sourceAddressPrefix explicitly.

This fix is for the [Issue#58 : Cluster Offers: Worker Nodes: make public/private IP configurable ](https://github.com/wls-eng/arm-oraclelinux-wls/issues/58)

### CODE REVIEW

**Comment by sanjaymantoor** [comment]
Submitted CI/CD trial run is working fine.
Refer https://github.com/sanjaymantoor/arm-oraclelinux-wls-admin/actions/runs/245794700

**Review by edburns — COMMENTED** [review]
Hello @sanjaymantoor this PR appears to remove a feature: the ability to customize the NSG at deployment time.  Why do we want to do this?

**Comment by sanjaymantoor** [comment]
Can you please reject the PR? I will re-work on it.

**Review by edburns — CHANGES_REQUESTED** [review]
Please re-work per external discussion.

**Comment by edburns** [comment]
Please re-work per external discussion.

**Pull request closed without merging**
